apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: xgboost-operator
  name: xgboost-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xgboost-operator
subjects:
- kind: ServiceAccount
  name: xgboost-operator
