apiVersion: extensions/v1
kind: Deployment
metadata:
  name: xgboost-operator
  namespace: xgboost-operator
  labels:
    app: xgboost-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgboost-operator
  template:
    metadata:
      labels:
        app: xgboost-operator
    spec:
      containers:
      - name: xgboost-operator
        command:
        - /root/manager
        - -mode=in-cluster
        image: gcr.io/kubeflow-images-public/xgboost-operator:v1.0
        imagePullPolicy: Always
      serviceAccountName: service-account
