apiVersion: "xgboostjob.kubeflow.org/v1alpha1"
kind: "XGBoostJob"
metadata:
  name: "xgboost-dist-test"
spec:
  xgbReplicaSpecs:
    Master:
      replicas: 1
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: xgboostjob
            image: gcr.io/kubeflow-ci/pytorch-dist-sendrecv-test:1.0
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
    Worker:
      replicas: 1
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: xgboostjob
            image: gcr.io/kubeflow-ci/pytorch-dist-sendrecv-test:1.0
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
